# Generated by Django 2.2 on 2020-10-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_auto_20201026_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
