# Generated by Django 2.2 on 2020-10-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_auto_20201026_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.TextField(default='None'),
        ),
    ]
