# Generated by Django 2.2 on 2020-10-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0005_auto_20201026_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
