# Generated by Django 2.2 on 2020-10-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0008_auto_20201026_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
